### ISSUE TITLE
Refine readme.md documentation

### ISSUE THREAD

**Issue by jack-berg** [newrelic/newrelic-opentelemetry-integration-java#36]
The readme.md should be refined as we prepare to funnel users to use this bundle. In particular, it should:

- Be consistent with new [docs.newrelic.com documentation](https://github.com/newrelic/newrelic-opentelemetry-integration-java/issues/35)
- Follow the structure of [opentelemetry-exporter-java](https://github.com/newrelic/opentelemetry-exporter-java) documentation and link to anchors when appropriate rather than copying code
- Add a working example (maybe with microservices-demo project?)

**Comment by gfuller1** [comment]
The structure is a little different than the exporter because it's an agent, which we have a separate template for here: https://github.com/newrelic/newrelic-repo-template/blob/main/README_agent.md. 

I added a simple example section that walks through building spring pet clinic and attaching the bundle agent.
